// API请求列表
export default {
    // 用户相关
    user_list: "/user/list",
    user_delete: "/user/delete",
    user_info: "/user/info",
    user_create: "/user/create",
    user_update: "/user/update",
    // 分类相关
    category_list: "/category/list",
    category_delete: "/category/delete",
    category_detail: "/category/detail",
    category_create: "/category/create",
    category_update: "/category/update",
    // 文章相关
    article_list: "/article/list",
    article_delete: "/article/delete",
    article_detail: "/article/detail",
    article_create: "/article/create",
    article_update: "/article/update",
    // 评论管理
    comment_list: "/comment/list",
    comment_delete: "/comment/delete",
    comment_detail: "/comment/detail",
    comment_create: "/comment/create",
    comment_update: "/comment/update",
    // 轮播相关
    banner_list: "/banner/list",
    banner_delete: "/banner/delete",
    banner_detail: "/banner/detail",
    banner_create: "/banner/create",
    banner_update: "/banner/update",
    // 配置相关
    config_list: "/config/list",
    config_delete: "/config/delete",
    config_detail: "/config/detail",
    config_create: "/config/create",
    config_update: "/config/update",
}
